title: Kira's Dungeons & Dragons
email: kira.hudson.v0@gmail.com
description: >-
  A Jekyll site for putting D&D-related content.
baseurl: "/dnd"
url: "https://kira-hudson.github.io"
github_username:  kira-hudson

# Collections
collections:
  crs:
    output: false
    sort_by: xp
  definitions:
    output: true
  homebrew:
    output: true
  worlds:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: homebrew
    values:
      layout: homebrew
  - scope:
      path: ""
      type: definitions
    values:
      layout: definition
  - scope:
      path: ""
    values:
      layout: default

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
